language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dictzip
install: 
  - pip install -r requirements-test.txt
script:
  - py.test --cov=stardicter
  - ./cizislova_tarball.sh --wrap 'coverage run --append'
  - ./dicts_info_tarball.sh --wrap 'coverage run --append' czech german
  - ./slovnik_de_tarball.sh --wrap 'coverage run --append'
  - ./slovnik_tarball.sh --wrap 'coverage run --append'
  - pep8 stardicter sdgen.py
  - pylint --reports=n stardicter sdgen.py || true
  - pyflakes stardicter sdgen.py
after_success:
  - coveralls
