language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dictzip
install: 
  - pip install --use-mirrors -r requirements-test.txt
script:
  - coverage run -m unittest discover
  - ./cizislova_tarball.sh --wrap 'coverage run --append'
  - ./dicts_info_tarball.sh --wrap 'coverage run --append' czech german
  - ./slovnik_de_tarball.sh --wrap 'coverage run --append'
  - ./slovnik_tarball.sh --wrap 'coverage run --append'
  - pep8 stardicter sdgen.py
  - pyflakes stardicter sdgen.py
after_success:
  - coveralls
